/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_dekstop;

/**
 *
 * @author refiahmadfauzan
 */
public class Menu extends javax.swing.JFrame {
    private String username, level;
    

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    public void setLevel(String level) {
        this.level = level;
        if (level.equals("siswa")) {
            menuJurusan.hide();
            menuKelas.hide();
            menuMapel.hide();
            menuUser.hide();
            subSiswa.hide();
            subInputNilai.hide();
            subNilai.setText("Lihat Nilai");
//            subSiswa.setText("Lihat Nilai");
        } else if (level.equals("guru")) {
            menuJurusan.hide();
            menuKelas.hide();
            menuMapel.hide();
            menuUser.hide();
            subSiswa.hide();
            subInputNilai.setText("Input Nilai");
            subNilai.setText("Lihat Nilai");
        } else if (level.equals("petugas")) {
            subInputNilai.hide();
            subNilai.setText("Lihat Nilai");
        } 
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSiswa = new javax.swing.JMenu();
        subSiswa = new javax.swing.JMenuItem();
        subNilai = new javax.swing.JMenuItem();
        subInputNilai = new javax.swing.JMenuItem();
        menuJurusan = new javax.swing.JMenu();
        subJurusan = new javax.swing.JMenuItem();
        menuKelas = new javax.swing.JMenu();
        subKelas = new javax.swing.JMenuItem();
        menuMapel = new javax.swing.JMenu();
        subMapel = new javax.swing.JMenuItem();
        menuUser = new javax.swing.JMenu();
        subUser = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 0));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        menuSiswa.setText("DATA SISWA");

        subSiswa.setText("Daftar Siswa");
        subSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subSiswaActionPerformed(evt);
            }
        });
        menuSiswa.add(subSiswa);

        subNilai.setText("Lihat Nilai");
        subNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subNilaiActionPerformed(evt);
            }
        });
        menuSiswa.add(subNilai);

        subInputNilai.setText("Input Nilai");
        subInputNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subInputNilaiActionPerformed(evt);
            }
        });
        menuSiswa.add(subInputNilai);

        jMenuBar1.add(menuSiswa);

        menuJurusan.setText("DATA JURUSAN");

        subJurusan.setText("Daftar Jurusan");
        subJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subJurusanActionPerformed(evt);
            }
        });
        menuJurusan.add(subJurusan);

        jMenuBar1.add(menuJurusan);

        menuKelas.setText("DATA KELAS");

        subKelas.setText("Daftar Kelas");
        subKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subKelasActionPerformed(evt);
            }
        });
        menuKelas.add(subKelas);

        jMenuBar1.add(menuKelas);

        menuMapel.setText("DATA MAPEL");

        subMapel.setText("Daftar Mapel");
        subMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMapelActionPerformed(evt);
            }
        });
        menuMapel.add(subMapel);

        jMenuBar1.add(menuMapel);

        menuUser.setText("DATA USER");

        subUser.setText("Daftar User");
        subUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subUserActionPerformed(evt);
            }
        });
        menuUser.add(subUser);

        jMenuBar1.add(menuUser);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subSiswaActionPerformed
        // TODO add your handling code here:
        DaftarSiswa siswa = new DaftarSiswa();
        panel.add(siswa);
        siswa.show();
    }//GEN-LAST:event_subSiswaActionPerformed

    private void subJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subJurusanActionPerformed
        // TODO add your handling code here:
        FormJurusan jurusan = new FormJurusan();
        panel.add(jurusan);
        jurusan.show();
    }//GEN-LAST:event_subJurusanActionPerformed

    private void subUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subUserActionPerformed
        // TODO add your handling code here:
        DaftarUser user = new DaftarUser();
        panel.add(user);
        user.show();
    }//GEN-LAST:event_subUserActionPerformed

    private void subMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMapelActionPerformed
        // TODO add your handling code here:
        DaftarMapel mapel = new DaftarMapel();
        panel.add(mapel);
        mapel.show();
    }//GEN-LAST:event_subMapelActionPerformed

    private void subKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subKelasActionPerformed
        // TODO add your handling code here:
        DaftarKelas kelas = new DaftarKelas();
        panel.add(kelas);
        kelas.show();
    }//GEN-LAST:event_subKelasActionPerformed

    private void subNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subNilaiActionPerformed
        // TODO add your handling code here:
        LihatNilai nilai = new LihatNilai();
        panel.add(nilai);
        nilai.show();
    }//GEN-LAST:event_subNilaiActionPerformed

    private void subInputNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subInputNilaiActionPerformed
        // TODO add your handling code here:
        FormNilai formNilai = new FormNilai();
        panel.add(formNilai);
        formNilai.show();
    }//GEN-LAST:event_subInputNilaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuJurusan;
    private javax.swing.JMenu menuKelas;
    private javax.swing.JMenu menuMapel;
    private javax.swing.JMenu menuSiswa;
    private javax.swing.JMenu menuUser;
    private javax.swing.JPanel panel;
    private javax.swing.JMenuItem subInputNilai;
    private javax.swing.JMenuItem subJurusan;
    private javax.swing.JMenuItem subKelas;
    private javax.swing.JMenuItem subMapel;
    private javax.swing.JMenuItem subNilai;
    private javax.swing.JMenuItem subSiswa;
    private javax.swing.JMenuItem subUser;
    // End of variables declaration//GEN-END:variables
}
