/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tugaspresentasi;


/**
 *
 * @author refiahmadfauzan
 */



public class Balok extends javax.swing.JInternalFrame {

    /**
     * Creates new form Balok
     */
    public Balok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputPanjang = new javax.swing.JTextField();
        inputLebar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputPilihan = new javax.swing.JComboBox<>();
        inputRadio1 = new javax.swing.JRadioButton();
        inputRadio2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        hasil = new javax.swing.JLabel();
        inputTinggi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Penerapan Polymorfisme");

        jLabel2.setText("Masukan panjang");

        inputPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPanjangActionPerformed(evt);
            }
        });

        jLabel3.setText("Masukan lebar");

        jLabel4.setText("PILIH BIDANG DATAR");

        inputPilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Pilih>", "Luas", "Keliling" }));
        inputPilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPilihanActionPerformed(evt);
            }
        });

        buttonGroup1.add(inputRadio1);
        inputRadio1.setText("Persegi Panjang");

        buttonGroup1.add(inputRadio2);
        inputRadio2.setText("Balok");
        inputRadio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRadio2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Masukan pilihan ");

        jLabel6.setText("Masukan tinggi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hasil)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(inputLebar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(inputRadio1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(inputRadio2))
                                .addComponent(inputPilihan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputLebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputRadio1)
                    .addComponent(inputRadio2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputPilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hasil)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPanjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPanjangActionPerformed

    private void inputPilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPilihanActionPerformed
        // TODO add your handling code here:
        Persegi kotak = new Persegi();
        UntukBalok balok = new UntukBalok();
        
        String pilihan;
        
        Double luas1, keliling1, luas2, keliling2;
        pilihan = (String)inputPilihan.getSelectedItem();
        
        if (inputRadio1.isSelected()) {
            switch(pilihan) {
                case "Luas" :
                    luas1 = kotak.hitungLuas();
                    hasil.setText("Luas Persegi Panjang : " + String.valueOf(luas1));
                    break;
                case "Keliling" :
                    keliling1 = kotak.hitungKeliling();
                    hasil.setText("keliling Persegi Panjang : " + String.valueOf(keliling1));
                    break;
            }
        }
        
        if (inputRadio2.isSelected()) {
            switch(pilihan) {
                case "Luas" :
                    luas2 = balok.hitungLuas();
                    hasil.setText("Luas Balok : " + String.valueOf(luas2));
                    break;
                case "Keliling" :
                    keliling2 = balok.hitungKeliling();
                    hasil.setText("Keliling Balok : " + String.valueOf(keliling2));
                    break;
             }
        }
        
    }//GEN-LAST:event_inputPilihanActionPerformed

    private void inputRadio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRadio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRadio2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JLabel hasil;
    private javax.swing.JTextField inputLebar;
    private javax.swing.JTextField inputPanjang;
    private javax.swing.JComboBox<String> inputPilihan;
    private javax.swing.JRadioButton inputRadio1;
    private javax.swing.JRadioButton inputRadio2;
    private javax.swing.JTextField inputTinggi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    private class UntukBalok extends Balok {
        double hitungLuas() {
            Double panjang, lebar, luas, tinggi;
            
            panjang = Double.parseDouble(inputPanjang.getText());
            lebar = Double.parseDouble(inputLebar.getText());
            tinggi = Double.parseDouble(inputTinggi.getText());
            luas = 2 * ((panjang * lebar) + (lebar * tinggi) + (panjang * tinggi));
            
            return luas;
        }
        
        double hitungKeliling() {
            Double panjang, lebar, tinggi, keliling;
            panjang = Double.parseDouble(inputPanjang.getText());
            lebar = Double.parseDouble(inputLebar.getText());
            tinggi = Double.parseDouble(inputTinggi.getText());
            keliling = 4 * (panjang + lebar + tinggi);
            
            return keliling;
        }
        
        
    }
    
    private class Persegi extends Balok {

          double hitungLuas() {
            Double panjang, lebar, luas;
            panjang = Double.parseDouble(inputPanjang.getText());
            lebar = Double.parseDouble(inputLebar.getText());
            luas = panjang * lebar;
            
            return luas;
        }
        
        double hitungKeliling() {
            Double panjang, lebar, keliling;
            panjang = Double.parseDouble(inputPanjang.getText());
            lebar = Double.parseDouble(inputLebar.getText());
            keliling = (2 * panjang) + (2 * lebar);
            
            return keliling;
        }
    }
}
